### ISSUE TITLE
No way to set "set" features

### ISSUE THREAD

**Issue by reckart** [lapps/org.lappsgrid.serialization#11]
The documentation for dependency structures indicates that the DependencyStructure type has a feature  called "dependencies" which is a set of the dependency relation IDs in the structure:

```
"annotations": [
         { "@type": "DependencyStructure",
           "id": "depstructure0",
           "start": 0,
           "end": 16,
           "features": {
              "type": "basic-dependencies",
              "dependencies": [ "dep0", "dep1", "dep2" ], <= HERE
```

Unfortunately, there is no appropriate `addFeature()` method in `Annotation`.

**Comment by reckart** [comment]
A workaround currently is:

```
Set<String> depRelIds = new TreeSet<>();
depStruct.getFeatures().put(Features.DependencyStructure.DEPENDENCIES, depRelIds);
```

**Comment by ksuderman** [comment]
That is currently the best work around.  However, we are already tracking this issue in #6 so I will go ahead a close this one.
