### ISSUE TITLE
getFeatureSet() and friends not returning null

### ISSUE THREAD

**Issue by reckart** [lapps/org.lappsgrid.serialization#14]
For code using the LAPPS serialization API, it would be rather convenient if the getFeatureSet/List/etc. methods always returned a collection (maybe an empty one) and never returned null.

**Comment by ksuderman** [comment]
Do you mean a `java.util.Collection`?  I.E.
```java
Collection getFeatureList(String name) { ... }
Collection getFeatureSet(String name) { ... }
```
Or simply that they always return a (possibly empty) collection (set, list, map,etc.)?

**Comment by reckart** [comment]
I mean returning an empty instance of the respective collection subtype (Set, List, Map). Depending on your preferences, this could be a "fresh" instance, or an unmodifiable singleton, e.g. as per Collections.EMPTY_SET or Collections.emptySet().

**Comment by ksuderman** [comment]
Thanks for the clarification.  I tend to lean toward a "fresh" (modifiable) instance, as I assume the new collection should become the new feature value.  Can you think of any instances where it would be useful to distinguish between "the feature has not been set" (i.e. is null) and "the feature has been explicitly set to an empty collection"?

**Comment by reckart** [comment]
In theory, there might be cases where one would like to check null vs. empty collection - but I can hardly imagine a good case. In WebAnno, we even go as far as considering null and empty string to be equivalent. If checking for null would really be necessary, a method like hasFeatureValue(name) could be added.
