### ISSUE TITLE
Method to resolve ID to Annotation

### ISSUE THREAD

**Issue by reckart** [lapps/org.lappsgrid.serialization#15]
Right now, I am scanning through the annotations in the view to find annotations with a certain ID, e.g.

```
view.getAnnotations().stream()
   .filter(a -> constituentIDs.contains(a.getId()))
   .forEach(con -> {...
``` 

I didn't find a method to do something like

```
constituentIDs.forEach(id -> {
   Annotation con = view.getAnnotation(id);
});
```

**Comment by ksuderman** [comment]
Rather than `View.getAnnotation(String id)` do you have any objections to `View.findById(String id)`?  This would allow other "findByX" methods that might also take a String parameter.  E.g. `View.findByAtType(String type)`

**Comment by reckart** [comment]
Some way to disambiguate the parameter semantics would be useful, yes.

**Comment by ksuderman** [comment]
Ok, I have pushed out 2.3.0-SNAPSHOT with all of the latest changes to the Sonatype snapshot repo.

**Comment by reckart** [comment]
I'll probably stick with the release versions until LIF support for DKPro Core 1.8.0 is final and then switch DKPro Core 1.9.0-SNAPSHOT (master) to the LAPPS snapshot artifacts.

**Comment by ksuderman** [comment]
Any chance you could take the 2.3.0-SNAPSHOT version out for a test just to make sure it is doing what you expect?

**Comment by reckart** [comment]
I just did a little test-drive of 2.3.0-SNAPSHOT.

The fact that getFeatureSet() (and friends) doesn't throw a checked exception anymore will allow me to remove one method. 

I didn't include any specific null-checks in my code so far, so the change that getFeatureSet() (etc.) doesn't return null anymore doesn't change my code, but avoids potential problems.

I assume that findById() may be something called rather often - backing it by a map instead of doing the linear scan may be better.
