### ISSUE TITLE
View#getContains

### ISSUE THREAD

**Issue by ksuderman** [lapps/org.lappsgrid.serialization#28]
Add the helper method `View#getContains` that returns the contains metadata from the view

**Comment by keighrim** [comment]
In current dev version, [this method](https://github.com/lapps/org.lappsgrid.serialization/blob/d03c2bbcd019f6f825c2ccebe6df7b8e6063d0c4/src/main/groovy/org/lappsgrid/serialization/lif/View.groovy#L153-L155) does not work. 

``` 
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to org.lappsgrid.serialization.lif.Contains
	at org.lappsgrid.serialization.lif.View.getContains(View.groovy:154)
... 
```
