### ISSUE TITLE
Contains needs an additional field

### ISSUE THREAD

**Issue by keighrim** [lapps/org.lappsgrid.serialization#29]
[`Contains` class](https://github.com/lapps/org.lappsgrid.serialization/blob/develop/src/main/groovy/org/lappsgrid/serialization/lif/Contains.groovy) needs a flexible place for the name of tagsets, which will be used for NE, POS, and maybe others.

**Comment by ksuderman** [comment]
Unfortunately commit fc2b812 introduces unwanted fields (`addititionalMetadata` and `additionalProperties`) in the JSON serialization.
