### ISSUE TITLE
Update for schema 1.1.0

### ISSUE THREAD

**Issue by ksuderman** [lapps/org.lappsgrid.serialization#43]

**Comment by ksuderman** [comment]
At least the following will be needed:

1. [ ] `Container` class must be able to serialize `$schema` field.
1. [ ] Remove `type` field from `Annotation`

**Comment by keighrim** [comment]
Adding `$schema` to the top-level of the `Container` means that tools using different versions of LIF-JSON schema must not be chained together? 
I think they should not.

**Comment by keighrim** [comment]
We also talked about adding `$schema` equivalent for vocabulary version.

**Comment by ksuderman** [comment]
I think the only way to do this via the Galaxy engine is to ensure all LAPPS tools installed support the new format.  The new Serializer should still be able to parse and load the old format so no data should be lost using new versions of the tools.

Now the question is - Should the Serializer ignore unknown fields in the JSON?  Currently the Serializer is *strict* and will reject JSON that contains fields it does not recognize.  Having a *lax* serializer that ignored unknown fields would allow old serializers to parse new formats, but it also opens the door for invalid LIF to be accepted.
