### ISSUE TITLE
Missing public method

### ISSUE THREAD

**Issue by keighrim** [lapps/org.lappsgrid.serialization#5]
According to LIF specification for tree [syntactic structure](http://lapps.github.io/interchange/phrase_structure-v1.html), `categorySet` field needs to be inside `views[x].metadata.contains`. However, there's no public method available in [`View`](https://github.com/lapps/org.lappsgrid.serialization/blob/develop/src/main/groovy/org/lappsgrid/serialization/lif/View.groovy) to add `categorySet` or any arbitrary fields there. Only method to access `contains` is [`addContains`](https://github.com/lapps/org.lappsgrid.serialization/blob/develop/src/main/groovy/org/lappsgrid/serialization/lif/View.groovy#L134), but it's taking `producer` and `type` only.

**Comment by keighrim** [comment]
This can be done using `getMetadata()` and manipulating the whole metadata. Issue closed.

**Comment by ksuderman** [comment]
While this can be done with `getMetadata()` we should reopen this issue in the future with proposed  helper methods for updating the metadata section.  At least we should have something like:
```java
public void setMetadata(String path, Object value);
```
where the `path` is an XPath like expression. E.g.
```java
view.setMetadata("contains/'http://vocab.lappsgrid.org/Token'/tagSet", "CLAWS7");
```
