### ISSUE TITLE
Helper methods

### ISSUE THREAD

**Issue by ksuderman** [lapps/org.lappsgrid.serialization#6]
Add helper methods to make working with the serialization objects more intuitive.
 - [x] Annotation.addFeature(String, List)
 - [x] Annotation.addFeature(String, Map)
 - [x] Annotation.addFeature(String,String)
 - [ ] Annotation.addFeature(String,Object) [optional]

**Comment by marcverhagen** [comment]
By default, the API sets @type, type and lable to the same thing.
The start and end attributes are set to -1 by default, in some cases this may not make sense.
Do we want identifier numbering support? Probably not, but do we want conventions like starting at 0 or 1 or stating with a letter that reflects the annotation type.

**Comment by ksuderman** [comment]
Actually, I think setting type, @type, and label to the same values was just me in the Gate and Stanford services.  I don't think the API does this, but we should double check.

**Comment by ksuderman** [comment]
As @reckart points out in #11 we also need. `Annotation.addFeature(String, Set)`.

Question: do we just want a one `addFeature()` method that handles any collection?  I.E.:
`Annotation.addFeature(String, Collection)`

Or even just `Annotation.addFeature(String,Object)` as feature values end up being stored in a `Map<Object,Object>` in the end?

**Comment by reckart** [comment]
IMHO it would be nice if the compiler could statically check whether the values passed is a ok. So I'd suggest addFeature(String, Set<String>).

**Comment by ksuderman** [comment]
Good point.  I think that is the way to go as well.
