### ISSUE TITLE
Need a way to keep @context mapping consistently

### ISSUE THREAD

**Issue by keighrim** [lapps/org.lappsgrid.serialization#7]
https://github.com/lapps/org.lappsgrid.serialization/blob/develop/src/main/groovy/org/lappsgrid/serialization/lif/Container.groovy#L88

I think we can keep a list of shortened strings in `Discriminator` package that mutually refer to [Discriminators.Uri](https://github.com/lapps/org.lappsgrid.discriminator/blob/master/src/main/java/org/lappsgrid/discriminator/Discriminators.java). 
Maybe something like `Alias` class, which keeps 1) a map between short keyword and full URI, and 2) a bunch of static strings that service developer can refer to. 
Ideally, if we can generate this `Alias` automatically whenever we update `Discriminators` class, that would be perfect. 
So for example, when a new URI string 
```java
public static final String TOKEN = "http://vocab.lappsgrid.org/Token"; 
```
is inserted, we take the string name and lower its case to make a default alias, then put it in Alias class.
```java
public class Alias {
    private Alias() { }
   
    ...
    public static final String TOKEN = "token";
    ...

    public static class AliasMap {
        public static final Map<String, String> aliasMap = new HashMap();
        ...
        aliasMap.put("token", "http://vocab.lappsgrid.org/Token");
        ...
    }
}
```
But at this point, it seems a lot of work. Maybe in the future.

How do you think?

**Comment by ksuderman** [comment]
While not very handy, at the moment the "short name" can be accessed via the DiscriminatorRegistry class.
```java
String shortName = DiscriminatorRegistry.getName(Uri.TOKEN);
```
I have created an issue in the Discriminator DSL project (oanc/org.lappsgrid.discriminator.dsl#3) to track this feature request.

**Comment by ksuderman** [comment]
This was implemented in the org.lappsgrid.discriminator module in Oct 2015. Aliases for the vocabulary URI are available in the static `Discriminators.Alias` class. E.g. `Discriminators.Alias.TOKEN`.
