### ISSUE TITLE
@type, type, label

### ISSUE THREAD

**Issue by keighrim** [lapps/org.lappsgrid.serialization#9]
https://github.com/lapps/org.lappsgrid.serialization/blob/develop/src/main/groovy/org/lappsgrid/serialization/lif/View.groovy#L116-L118

Current implementation grants the same value for these three fields. However, I believe, from our recent discussion, only @type is a necessary field. 
Should we keep the other two? If we removing these, changing signature (`String type` -> `String atType`) also would be more self-explaining.

**Comment by ksuderman** [comment]
Fixed version pushed out as 2.1.0-SNAPSHOT

**Comment by ksuderman** [comment]
Released in v2.1.0
